const rub=n=>new Intl.NumberFormat('ru-RU').format(n)+' ₽';
function calculateEstimate({zone,tonnage,bodytype,stops,loaders}) {
 const range=TARIFFS.baseRanges[tonnage],factor=TARIFFS.zoneFactors[zone];
 if(!range||!factor||bodytype==='special'||Number(stops)>=3)return {individual:true};
 const multiplier=factor+Number(stops)*TARIFFS.extraStopFactor;
 return {individual:false,low:Math.round(range[0]*multiplier/TARIFFS.roundTo)*TARIFFS.roundTo,high:Math.round(range[1]*multiplier/TARIFFS.roundTo)*TARIFFS.roundTo,loadersExtra:loaders!=='no',openBody:bodytype==='open',base:range,factor,stopFactor:Number(stops)*TARIFFS.extraStopFactor};
}
function calcValues(){return Object.fromEntries(['zone','tonnage','bodytype','stops','loaders'].map(id=>[id,document.getElementById(id).value]))}
function renderEstimate(){const v=calcValues(),e=calculateEstimate(v);document.getElementById('loader-details').hidden=v.loaders==='no';document.getElementById('estimate-price').textContent=e.individual?'Индивидуальный расчёт':rub(e.low)+' – '+rub(e.high);document.getElementById('estimate-note').textContent=e.individual?'Для этого заказа нужна отдельная оценка. Укажите адреса и груз в заявке или позвоните.':(e.loadersExtra?'Грузчики — отдельно. ':'Погрузка и разгрузка силами заказчика. ')+(e.openBody?'Ставку на бортовую машину уточним у перевозчика. ':'Для выбора кузова нужны размеры груза. ');document.getElementById('estimate-breakdown').textContent=e.individual?'':'Учтены машина, направление и дополнительные адреса. Гидроборт и другие специальные работы — отдельно.';return e}
document.querySelectorAll('#calculator select').forEach(s=>s.addEventListener('change',renderEstimate));
document.getElementById('use-estimate').onclick=()=>{const v=calcValues(),e=renderEstimate();const labels=['zone','tonnage','bodytype','stops','loaders'].map(id=>{const s=document.getElementById(id);return s.selectedOptions[0].textContent});const details=v.loaders==='no'?'':[document.getElementById('floors').value,document.getElementById('heavy').value].filter(Boolean).join('; ');document.getElementById('cargo').value=labels.join('; ')+(details?'; '+details:'')+(e.individual?'; нужен индивидуальный расчёт':'; ориентир транспорта '+rub(e.low)+'–'+rub(e.high));document.getElementById('request').scrollIntoView({behavior:'smooth'});document.getElementById('from').focus({preventScroll:true})};
if(INITIAL_MODE==='small'||INITIAL_MODE==='large'){[...document.getElementById('tonnage').options].forEach(o=>{if(o.value!=='unknown'&&((INITIAL_MODE==='small'&&Number(o.value)>3)||(INITIAL_MODE==='large'&&Number(o.value)<5)))o.remove()})}
document.getElementById('tonnage').value=INITIAL_MODE==='large'?'5':'1.5';if(INITIAL_MODE==='route')document.getElementById('zone').value='moscow';renderEstimate();
